# Learning the basics of Pandas

Pandas is an open-source library in Python that is used for data analysis and manipulation. To start using this library, we must ensure it is installed on our computers. Use the following command to install pandas:

In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: pytz>=2020.1 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.3)
Requirement already satisfied: numpy>=1.22.4 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
WARNING: You are using pip version 21.2.4; however, version 25.3 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

As you can see above, the computer already has pandas, so we are all set! Now we must import pandas, and we can do this using the following command:

In [2]:
import pandas as pd

Note: the pandas' community has agreed to refer to pandas as pd in all official documentation.

Next, we learn how to load our dataset using pandas. The type of file we are working with here is a comma-separated values file, also known as a csv file.
We load this data by using the following command: <b>df = pd.read_csv('filename.csv')</b>

In [3]:
df = pd.read_csv('data/penguins_size.csv')

We have loaded the data set 'penguins_size' in pandas as a pandas dataframe object named <b>df</b>. Next, we can take a quick look at our data frame:

In [4]:
df

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

Also, we can only look at the first n number of rows of our data frame using the <b>pd.head(n)</b> command, or we can see the bottom n number of rows using the <b>df.tail(n)</b> command.

In [5]:
df.head(5)

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [6]:
df.tail(5)

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

Now that we have seen our data frame, here are some other things we can do to gain a good feel of the data/data frame.

We can find out the size of our data frame by using the .shape attribute. It returns the number of rows and the number of columns.

In [7]:
df.shape

(344, 7)

We can also figure out more details about the data frame using the <b>.info()</b> method. This method prints out information about the data frame. <br>
For example, it includes the number of columns, the data type of each column, how much memory is being used, the range index, and the number of non-null values, which means the number of cells each column has.

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   culmen_length_mm   342 non-null    float64
 3   culmen_depth_mm    342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

# Accesing and modifying  columns and rows

There are multiple ways to access columns and rows in pandas. We start by accessing columns; there are two main ways to access columns in pandas. The first way is to access it as a series, i.e., by referring to it as an attribute. For example, <b>data-frame-object-name.column_name</b>. Accessing it this way also gives the details about the column. These details include the column's name, the number of rows present in that column, and the data type of the values in that column.

In [9]:
df.species

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 344, dtype: object

Here we can observe that the data type of this column is an object. It means that it is a collection of multiple different data types.

Here there is the second way we can access individual columns. We can access it as another data frame using the <b>df[['column_name]]</b>. We do this by calling it within a Python list.

In [10]:
df[['species']]

    species
0    Adelie
1    Adelie
2    Adelie
3    Adelie
4    Adelie
..      ...
339  Gentoo
340  Gentoo
341  Gentoo
342  Gentoo
343  Gentoo

[344 rows x 1 columns]

This technique allows us to access multiple columns, for example:

In [11]:
df[['species','island']]

    species     island
0    Adelie  Torgersen
1    Adelie  Torgersen
2    Adelie  Torgersen
3    Adelie  Torgersen
4    Adelie  Torgersen
..      ...        ...
339  Gentoo     Biscoe
340  Gentoo     Biscoe
341  Gentoo     Biscoe
342  Gentoo     Biscoe
343  Gentoo     Biscoe

[344 rows x 2 columns]

If we want to find out the names of all columns in the data frame, we can use <b>df.columns</b>.

In [12]:
df.columns

Index(['species', 'island', 'culmen_length_mm', 'culmen_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

We can also drop columns from our dataframe using the <b>.drop()</b> method. Additionally, the <b>.drop()</b> method can also be used to drop rows. It is done by the methods' parameters. Parameters are essentially values of datatypes that we input into the method.

If we want to drop a column, we modify the columns parameter by doing this - <b>df.drop(columns = ['column_1','column_2'])</b>

@(Reprint df so that we can see that the columns are dropped)

In [13]:
df.drop(columns = ['body_mass_g','sex'])

    species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm
0    Adelie  Torgersen              39.1             18.7              181.0
1    Adelie  Torgersen              39.5             17.4              186.0
2    Adelie  Torgersen              40.3             18.0              195.0
3    Adelie  Torgersen               NaN              NaN                NaN
4    Adelie  Torgersen              36.7             19.3              193.0
..      ...        ...               ...              ...                ...
339  Gentoo     Biscoe               NaN              NaN                NaN
340  Gentoo     Biscoe              46.8             14.3              215.0
341  Gentoo     Biscoe              50.4             15.7              222.0
342  Gentoo     Biscoe              45.2             14.8              212.0
343  Gentoo     Biscoe              49.9             16.1              213.0

[344 rows x 5 columns]

In [14]:
df

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

Let us look at how we can move columns around. <br>
We go through two ways of doing this. The first way is to specify the order you want - <b>df[['1st_column' , '2nd_column' , 3rd_column']]</b>. <br>
Here is an example:

In [15]:
df_rearranged_1 = df[['island','species','culmen_depth_mm','culmen_length_mm','flipper_length_mm','sex','body_mass_g']]

In [16]:
df_rearranged_1

,island,species,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Torgersen,Adelie,18.7,39.1,181.0,MALE,3750.0
1,Torgersen,Adelie,17.4,39.5,186.0,FEMALE,3800.0
2,Torgersen,Adelie,18.0,40.3,195.0,FEMALE,3250.0
3,Torgersen,Adelie,NaN,NaN,NaN,NaN,NaN
4,Torgersen,Adelie,19.3,36.7,193.0,FEMALE,3450.0
...,...,...,...,...,...,...,...
339,Biscoe,Gentoo,NaN,NaN,NaN,NaN,NaN
340,Biscoe,Gentoo,14.3,46.8,215.0,FEMALE,4850.0
341,Biscoe,Gentoo,15.7,50.4,222.0,MALE,5750.0
342,Biscoe,Gentoo,14.8,45.2,212.0,FEMALE,5200.0
343,Biscoe,Gentoo,16.1,49.9,213.0,MALE,5400.0

The other method would be - <b>df.pop('column_name')</b> and <b> .insert(column_index,'column_name',value)</b> method. <br> An example:

In [17]:
df=df_rearranged_1

In [18]:
column_being_moved = df.pop('sex')

In [19]:
df

,island,species,culmen_depth_mm,culmen_length_mm,flipper_length_mm,body_mass_g
0,Torgersen,Adelie,18.7,39.1,181.0,3750.0
1,Torgersen,Adelie,17.4,39.5,186.0,3800.0
2,Torgersen,Adelie,18.0,40.3,195.0,3250.0
3,Torgersen,Adelie,NaN,NaN,NaN,NaN
4,Torgersen,Adelie,19.3,36.7,193.0,3450.0
...,...,...,...,...,...,...
339,Biscoe,Gentoo,NaN,NaN,NaN,NaN
340,Biscoe,Gentoo,14.3,46.8,215.0,4850.0
341,Biscoe,Gentoo,15.7,50.4,222.0,5750.0
342,Biscoe,Gentoo,14.8,45.2,212.0,5200.0
343,Biscoe,Gentoo,16.1,49.9,213.0,5400.0

In [19]:
df.insert(0,'sex',column_being_moved)

In [20]:
df

,sex,island,species,culmen_depth_mm,culmen_length_mm,flipper_length_mm,body_mass_g
0,MALE,Torgersen,Adelie,18.7,39.1,181.0,3750.0
1,FEMALE,Torgersen,Adelie,17.4,39.5,186.0,3800.0
2,FEMALE,Torgersen,Adelie,18.0,40.3,195.0,3250.0
3,NaN,Torgersen,Adelie,NaN,NaN,NaN,NaN
4,FEMALE,Torgersen,Adelie,19.3,36.7,193.0,3450.0
...,...,...,...,...,...,...,...
339,NaN,Biscoe,Gentoo,NaN,NaN,NaN,NaN
340,FEMALE,Biscoe,Gentoo,14.3,46.8,215.0,4850.0
341,MALE,Biscoe,Gentoo,15.7,50.4,222.0,5750.0
342,FEMALE,Biscoe,Gentoo,14.8,45.2,212.0,5200.0
343,MALE,Biscoe,Gentoo,16.1,49.9,213.0,5400.0

In [21]:
column_being_moved = df.pop('sex')
df.insert(5,'sex',column_being_moved)

Next, we learn how to access different rows. There are multiple ways to do so. We can use the <b>.iloc</b> method or the <b>.loc</b> method. <br>
First, we will use the <b>.iloc</b> method.

Note: <b>iloc</b> stands for integer location. It allows users to grab values from a specific row: we specify which row we are interested in by inputting an integer in the square brackets. This function returns a series that contains the rows' values.

In [22]:
df.iloc[0]

island               Torgersen
species                 Adelie
culmen_depth_mm           18.7
culmen_length_mm          39.1
flipper_length_mm        181.0
sex                       MALE
body_mass_g             3750.0
Name: 0, dtype: object

Again, we can treat the first row as a series. <br>
However, we can also treat it as a dataframe by enclosing it in square brackets to create a list - like this:

In [23]:
df.iloc[[0]]

,island,species,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Torgersen,Adelie,18.7,39.1,181.0,MALE,3750.0

We can also call multiple different rows by adding values in the list:

In [24]:
df.iloc[[0, 220 , 302]]

,island,species,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Torgersen,Adelie,18.7,39.1,181.0,MALE,3750.0
220,Biscoe,Gentoo,13.2,46.1,211.0,FEMALE,4500.0
302,Biscoe,Gentoo,14.6,47.4,212.0,FEMALE,4725.0

Let us try to be more specific and call different rows and particular columns in that row. Note <b>'sex'</b> is located at index 5, and <b>'body_mass_g'</b> is located at index 6:

In [25]:
df.iloc[[0, 220, 303],[5, 6]]

        sex  body_mass_g
0      MALE       3750.0
220  FEMALE       4500.0
303    MALE       5350.0

Now, let us take a look at the <b>.loc</b> method

In [26]:
df.loc[0]

island               Torgersen
species                 Adelie
culmen_depth_mm           18.7
culmen_length_mm          39.1
flipper_length_mm        181.0
sex                       MALE
body_mass_g             3750.0
Name: 0, dtype: object

In [27]:
df.loc[[0]]

,island,species,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Torgersen,Adelie,18.7,39.1,181.0,MALE,3750.0

As we can see, the <b>.loc</b> method and the <b>.iloc</b> method are essentially the same. However, that changes when we start including columns in the equation. In the <b>.loc</b> method, we use their names rather than their indexes if we want to access columns.

In [28]:
df.loc[[0, 220, 303], ['island','flipper_length_mm']]

        island  flipper_length_mm
0    Torgersen              181.0
220     Biscoe              211.0
303     Biscoe              224.0

# Changing Indexes

The index of an array corresponds to the row's number of the dataframe. There are multiple things we can do when working with indexes. We can change the order in which pandas prints the dataframe out. For example, we can print it out in descending using the <b>.sort_index( ascending = 'False')</b>.

In [29]:
df.sort_index(ascending = False)

,island,species,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
343,Biscoe,Gentoo,16.1,49.9,213.0,MALE,5400.0
342,Biscoe,Gentoo,14.8,45.2,212.0,FEMALE,5200.0
341,Biscoe,Gentoo,15.7,50.4,222.0,MALE,5750.0
340,Biscoe,Gentoo,14.3,46.8,215.0,FEMALE,4850.0
339,Biscoe,Gentoo,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
4,Torgersen,Adelie,19.3,36.7,193.0,FEMALE,3450.0
3,Torgersen,Adelie,NaN,NaN,NaN,NaN,NaN
2,Torgersen,Adelie,18.0,40.3,195.0,FEMALE,3250.0
1,Torgersen,Adelie,17.4,39.5,186.0,FEMALE,3800.0
0,Torgersen,Adelie,18.7,39.1,181.0,MALE,3750.0

Also, we are able to change the index values. We can set it up to the pre-existing column values using the <b>.set_index()</b> method: <b>df.set_index('column_name')</b>.

In [30]:
df.set_index('body_mass_g')

,island,species,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex
body_mass_g,,,,,,
3750.0,Torgersen,Adelie,18.7,39.1,181.0,MALE
3800.0,Torgersen,Adelie,17.4,39.5,186.0,FEMALE
3250.0,Torgersen,Adelie,18.0,40.3,195.0,FEMALE
NaN,Torgersen,Adelie,NaN,NaN,NaN,NaN
3450.0,Torgersen,Adelie,19.3,36.7,193.0,FEMALE
...,...,...,...,...,...,...
NaN,Biscoe,Gentoo,NaN,NaN,NaN,NaN
4850.0,Biscoe,Gentoo,14.3,46.8,215.0,FEMALE
5750.0,Biscoe,Gentoo,15.7,50.4,222.0,MALE
5200.0,Biscoe,Gentoo,14.8,45.2,212.0,FEMALE
5400.0,Biscoe,Gentoo,16.1,49.9,213.0,MALE

This change is not permanent unless you modify the <b>inplace</b> parameter:

In [31]:
df.set_index('body_mass_g', inplace = True)
df

,island,species,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex
body_mass_g,,,,,,
3750.0,Torgersen,Adelie,18.7,39.1,181.0,MALE
3800.0,Torgersen,Adelie,17.4,39.5,186.0,FEMALE
3250.0,Torgersen,Adelie,18.0,40.3,195.0,FEMALE
NaN,Torgersen,Adelie,NaN,NaN,NaN,NaN
3450.0,Torgersen,Adelie,19.3,36.7,193.0,FEMALE
...,...,...,...,...,...,...
NaN,Biscoe,Gentoo,NaN,NaN,NaN,NaN
4850.0,Biscoe,Gentoo,14.3,46.8,215.0,FEMALE
5750.0,Biscoe,Gentoo,15.7,50.4,222.0,MALE
5200.0,Biscoe,Gentoo,14.8,45.2,212.0,FEMALE
5400.0,Biscoe,Gentoo,16.1,49.9,213.0,MALE

To reset our dataframe index to default parameters, we use the <b>reset_index()</b> method. If we want this change to be permanent, we set the <b>inplace</b> parameter to <b>True</b>.

In [32]:
df.reset_index(inplace = True)

In [33]:
df

,body_mass_g,island,species,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex
0,3750.0,Torgersen,Adelie,18.7,39.1,181.0,MALE
1,3800.0,Torgersen,Adelie,17.4,39.5,186.0,FEMALE
2,3250.0,Torgersen,Adelie,18.0,40.3,195.0,FEMALE
3,NaN,Torgersen,Adelie,NaN,NaN,NaN,NaN
4,3450.0,Torgersen,Adelie,19.3,36.7,193.0,FEMALE
...,...,...,...,...,...,...,...
339,NaN,Biscoe,Gentoo,NaN,NaN,NaN,NaN
340,4850.0,Biscoe,Gentoo,14.3,46.8,215.0,FEMALE
341,5750.0,Biscoe,Gentoo,15.7,50.4,222.0,MALE
342,5200.0,Biscoe,Gentoo,14.8,45.2,212.0,FEMALE
343,5400.0,Biscoe,Gentoo,16.1,49.9,213.0,MALE

In [34]:
column_being_moved = df.pop('body_mass_g')
df.insert(6,'body_mass_g',column_being_moved)
df

,island,species,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Torgersen,Adelie,18.7,39.1,181.0,MALE,3750.0
1,Torgersen,Adelie,17.4,39.5,186.0,FEMALE,3800.0
2,Torgersen,Adelie,18.0,40.3,195.0,FEMALE,3250.0
3,Torgersen,Adelie,NaN,NaN,NaN,NaN,NaN
4,Torgersen,Adelie,19.3,36.7,193.0,FEMALE,3450.0
...,...,...,...,...,...,...,...
339,Biscoe,Gentoo,NaN,NaN,NaN,NaN,NaN
340,Biscoe,Gentoo,14.3,46.8,215.0,FEMALE,4850.0
341,Biscoe,Gentoo,15.7,50.4,222.0,MALE,5750.0
342,Biscoe,Gentoo,14.8,45.2,212.0,FEMALE,5200.0
343,Biscoe,Gentoo,16.1,49.9,213.0,MALE,5400.0

Suppose we want the index of each row to be a column that consists of letters with the ability to sort those in alphabetic ascending or descending order. In that case, we can use the <b>.sort_index()</b> method by modifying the ascending parameter. Let us look at it in ascending order first.

In [35]:
df.set_index('island', inplace = True)

In [36]:
df

,species,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
island,,,,,,
Torgersen,Adelie,18.7,39.1,181.0,MALE,3750.0
Torgersen,Adelie,17.4,39.5,186.0,FEMALE,3800.0
Torgersen,Adelie,18.0,40.3,195.0,FEMALE,3250.0
Torgersen,Adelie,NaN,NaN,NaN,NaN,NaN
Torgersen,Adelie,19.3,36.7,193.0,FEMALE,3450.0
...,...,...,...,...,...,...
Biscoe,Gentoo,NaN,NaN,NaN,NaN,NaN
Biscoe,Gentoo,14.3,46.8,215.0,FEMALE,4850.0
Biscoe,Gentoo,15.7,50.4,222.0,MALE,5750.0
Biscoe,Gentoo,14.8,45.2,212.0,FEMALE,5200.0
Biscoe,Gentoo,16.1,49.9,213.0,MALE,5400.0

In the ascending alphabetical order

In [37]:
df.sort_index()

,species,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
island,,,,,,
Biscoe,Gentoo,16.1,49.9,213.0,MALE,5400.0
Biscoe,Adelie,17.0,38.1,181.0,FEMALE,3175.0
Biscoe,Adelie,19.0,43.2,197.0,MALE,4775.0
Biscoe,Adelie,16.5,38.1,198.0,FEMALE,3825.0
Biscoe,Adelie,20.3,45.6,191.0,MALE,4600.0
...,...,...,...,...,...,...
Torgersen,Adelie,17.2,39.6,196.0,FEMALE,3550.0
Torgersen,Adelie,18.4,39.7,190.0,MALE,3900.0
Torgersen,Adelie,19.0,33.5,190.0,FEMALE,3600.0
Torgersen,Adelie,16.6,35.9,190.0,FEMALE,3050.0
Torgersen,Adelie,18.7,39.1,181.0,MALE,3750.0

... and in the descending alphabetical order

In [38]:
df.sort_index(ascending = False)

,species,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
island,,,,,,
Torgersen,Adelie,18.7,39.1,181.0,MALE,3750.0
Torgersen,Adelie,17.0,38.6,188.0,FEMALE,2900.0
Torgersen,Adelie,19.0,33.5,190.0,FEMALE,3600.0
Torgersen,Adelie,18.4,39.7,190.0,MALE,3900.0
Torgersen,Adelie,17.2,39.6,196.0,FEMALE,3550.0
...,...,...,...,...,...,...
Biscoe,Gentoo,13.7,45.5,214.0,FEMALE,4650.0
Biscoe,Gentoo,14.6,48.4,213.0,MALE,5850.0
Biscoe,Gentoo,14.6,45.8,210.0,FEMALE,4200.0
Biscoe,Gentoo,15.7,49.3,217.0,MALE,5850.0
Biscoe,Gentoo,16.1,49.9,213.0,MALE,5400.0

In [39]:
df.reset_index(inplace = True)

In [40]:
column_being_moved = df.pop('island')
df.insert(1,'island',column_being_moved)

Now lets take a look at filtering...

# Filtering

Filtering dataframe removes unwanted data; we can do this in multiple ways. Here, there are some examples.

For example, let us say we want to seize the data of the Gentoo species of penguins. We set up a filter in the following way. <br>
At first, we make a variable corresponding to the data we want. In this case, the data is about the Gentoo species

In [41]:
filter = (df['species'] == 'Gentoo')

... now we apply to it to our dataframe

In [42]:
df[filter]

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
220,Gentoo,Biscoe,13.2,46.1,211.0,FEMALE,4500.0
221,Gentoo,Biscoe,16.3,50.0,230.0,MALE,5700.0
222,Gentoo,Biscoe,14.1,48.7,210.0,FEMALE,4450.0
223,Gentoo,Biscoe,15.2,50.0,218.0,MALE,5700.0
224,Gentoo,Biscoe,14.5,47.6,215.0,MALE,5400.0
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,14.3,46.8,215.0,FEMALE,4850.0
341,Gentoo,Biscoe,15.7,50.4,222.0,MALE,5750.0
342,Gentoo,Biscoe,14.8,45.2,212.0,FEMALE,5200.0
343,Gentoo,Biscoe,16.1,49.9,213.0,MALE,5400.0

We can also do this using the <b>.loc</b> method

In [43]:
df.loc[filter]

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
220,Gentoo,Biscoe,13.2,46.1,211.0,FEMALE,4500.0
221,Gentoo,Biscoe,16.3,50.0,230.0,MALE,5700.0
222,Gentoo,Biscoe,14.1,48.7,210.0,FEMALE,4450.0
223,Gentoo,Biscoe,15.2,50.0,218.0,MALE,5700.0
224,Gentoo,Biscoe,14.5,47.6,215.0,MALE,5400.0
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,14.3,46.8,215.0,FEMALE,4850.0
341,Gentoo,Biscoe,15.7,50.4,222.0,MALE,5750.0
342,Gentoo,Biscoe,14.8,45.2,212.0,FEMALE,5200.0
343,Gentoo,Biscoe,16.1,49.9,213.0,MALE,5400.0

When <b>.loc</b> is used, we can become more specific with our filter by adding specific columns

In [44]:
df.loc[filter,['island','sex']]

     island     sex
220  Biscoe  FEMALE
221  Biscoe    MALE
222  Biscoe  FEMALE
223  Biscoe    MALE
224  Biscoe    MALE
..      ...     ...
339  Biscoe     NaN
340  Biscoe  FEMALE
341  Biscoe    MALE
342  Biscoe  FEMALE
343  Biscoe    MALE

[124 rows x 2 columns]

Now, we want data corresponding not only to a specific species but also to the sex of penguins - especially the species Adelie and Male.

In [45]:
filter = (df['species'] == 'Adelie') & (df['sex'] == 'MALE')
df.loc[filter]

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Adelie,Torgersen,18.7,39.1,181.0,MALE,3750.0
5,Adelie,Torgersen,20.6,39.3,190.0,MALE,3650.0
7,Adelie,Torgersen,19.6,39.2,195.0,MALE,4675.0
13,Adelie,Torgersen,21.2,38.6,191.0,MALE,3800.0
14,Adelie,Torgersen,21.1,34.6,198.0,MALE,4400.0
...,...,...,...,...,...,...,...
143,Adelie,Dream,17.0,40.7,190.0,MALE,3725.0
145,Adelie,Dream,18.7,39.0,185.0,MALE,3650.0
146,Adelie,Dream,18.6,39.2,190.0,MALE,4250.0
149,Adelie,Dream,18.1,37.8,193.0,MALE,3750.0
151,Adelie,Dream,18.5,41.5,201.0,MALE,4000.0

Or ... we want a dataframe with the penguins from the Dream or Torgersen islands

In [46]:
filter = (df['island'] == 'Torgersen') | (df['island'] == 'Dream')

In [47]:
df[filter]

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Adelie,Torgersen,18.7,39.1,181.0,MALE,3750.0
1,Adelie,Torgersen,17.4,39.5,186.0,FEMALE,3800.0
2,Adelie,Torgersen,18.0,40.3,195.0,FEMALE,3250.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,19.3,36.7,193.0,FEMALE,3450.0
...,...,...,...,...,...,...,...
215,Chinstrap,Dream,19.8,55.8,207.0,MALE,4000.0
216,Chinstrap,Dream,18.1,43.5,202.0,FEMALE,3400.0
217,Chinstrap,Dream,18.2,49.6,193.0,MALE,3775.0
218,Chinstrap,Dream,19.0,50.8,210.0,MALE,4100.0
219,Chinstrap,Dream,18.7,50.2,198.0,FEMALE,3775.0

Or ... we want to work with data about penguins with a flipper length greater than 200. So, we could filter out the data like this

In [48]:
filter = df['flipper_length_mm'] > 200

In [49]:
df[filter]

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
90,Adelie,Dream,18.0,35.7,202.0,FEMALE,3550.0
91,Adelie,Dream,18.1,41.1,205.0,MALE,4300.0
95,Adelie,Dream,18.9,40.8,208.0,MALE,4300.0
101,Adelie,Biscoe,20.0,41.0,203.0,MALE,4725.0
123,Adelie,Torgersen,18.5,41.4,202.0,MALE,3875.0
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,13.7,47.2,214.0,FEMALE,4925.0
340,Gentoo,Biscoe,14.3,46.8,215.0,FEMALE,4850.0
341,Gentoo,Biscoe,15.7,50.4,222.0,MALE,5750.0
342,Gentoo,Biscoe,14.8,45.2,212.0,FEMALE,5200.0
343,Gentoo,Biscoe,16.1,49.9,213.0,MALE,5400.0

Now, we would like to work with data about penguins that have a flipper length greater than 200mm AND a body mass less than 4000g

In [50]:
filter = ((df['flipper_length_mm'] > 200) & (df['body_mass_g'] < 4000))

In [51]:
df[filter]

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
90,Adelie,Dream,18.0,35.7,202.0,FEMALE,3550.0
123,Adelie,Torgersen,18.5,41.4,202.0,MALE,3875.0
192,Chinstrap,Dream,19.5,49.0,210.0,MALE,3950.0
203,Chinstrap,Dream,19.0,51.4,201.0,MALE,3950.0
210,Chinstrap,Dream,18.8,50.2,202.0,MALE,3800.0
212,Chinstrap,Dream,19.5,51.9,206.0,MALE,3950.0
216,Chinstrap,Dream,18.1,43.5,202.0,FEMALE,3400.0
260,Gentoo,Biscoe,13.7,42.7,208.0,FEMALE,3950.0

Let us look at filtering when working with strings ...

We want to work with data from species that have the letter <b>e</b> in their names; we would use the <b>.str.contains('letter')</b>.

In [52]:
filter = df['species'].str.contains('e')

In [53]:
df[filter]

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Adelie,Torgersen,18.7,39.1,181.0,MALE,3750.0
1,Adelie,Torgersen,17.4,39.5,186.0,FEMALE,3800.0
2,Adelie,Torgersen,18.0,40.3,195.0,FEMALE,3250.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,19.3,36.7,193.0,FEMALE,3450.0
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,14.3,46.8,215.0,FEMALE,4850.0
341,Gentoo,Biscoe,15.7,50.4,222.0,MALE,5750.0
342,Gentoo,Biscoe,14.8,45.2,212.0,FEMALE,5200.0
343,Gentoo,Biscoe,16.1,49.9,213.0,MALE,5400.0

Or ... we want to work with data about penguins from an island that contains a string of letters; we would use the <b>.str.contains('string')</b>.

In [54]:
filter = df['island'].str.contains('ea')

In [55]:
df[filter]

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
30,Adelie,Dream,16.7,39.5,178.0,FEMALE,3250.0
31,Adelie,Dream,18.1,37.2,178.0,MALE,3900.0
32,Adelie,Dream,17.8,39.5,188.0,FEMALE,3300.0
33,Adelie,Dream,18.9,40.9,184.0,MALE,3900.0
34,Adelie,Dream,17.0,36.4,195.0,FEMALE,3325.0
...,...,...,...,...,...,...,...
215,Chinstrap,Dream,19.8,55.8,207.0,MALE,4000.0
216,Chinstrap,Dream,18.1,43.5,202.0,FEMALE,3400.0
217,Chinstrap,Dream,18.2,49.6,193.0,MALE,3775.0
218,Chinstrap,Dream,19.0,50.8,210.0,MALE,4100.0
219,Chinstrap,Dream,18.7,50.2,198.0,FEMALE,3775.0

If we want to work with data from a specific column that has a string starting with a specific letter or string;
we would use the <b>.str.startswith('letter')</b> or <b>.str.startswith('string')</b>.

In [56]:
filter = df['species'].str.startswith('A')

In [57]:
df[filter]

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Adelie,Torgersen,18.7,39.1,181.0,MALE,3750.0
1,Adelie,Torgersen,17.4,39.5,186.0,FEMALE,3800.0
2,Adelie,Torgersen,18.0,40.3,195.0,FEMALE,3250.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,19.3,36.7,193.0,FEMALE,3450.0
...,...,...,...,...,...,...,...
147,Adelie,Dream,18.4,36.6,184.0,FEMALE,3475.0
148,Adelie,Dream,17.8,36.0,195.0,FEMALE,3450.0
149,Adelie,Dream,18.1,37.8,193.0,MALE,3750.0
150,Adelie,Dream,17.1,36.0,187.0,FEMALE,3700.0
151,Adelie,Dream,18.5,41.5,201.0,MALE,4000.0

Another approach: if we want to work with data that ends with a string - we use <b>.str.endswith('letter')</b> or <b>.str.endswith('string')</b>.

For example, we have an array of column names we would like to work with - we could use the <b>.isin(array)</b> method.

In [58]:
array = ['Torgersen','Dream']

In [59]:
filter = df['island'].isin(['Torgersen','Dream'])

In [60]:
df[filter]

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Adelie,Torgersen,18.7,39.1,181.0,MALE,3750.0
1,Adelie,Torgersen,17.4,39.5,186.0,FEMALE,3800.0
2,Adelie,Torgersen,18.0,40.3,195.0,FEMALE,3250.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,19.3,36.7,193.0,FEMALE,3450.0
...,...,...,...,...,...,...,...
215,Chinstrap,Dream,19.8,55.8,207.0,MALE,4000.0
216,Chinstrap,Dream,18.1,43.5,202.0,FEMALE,3400.0
217,Chinstrap,Dream,18.2,49.6,193.0,MALE,3775.0
218,Chinstrap,Dream,19.0,50.8,210.0,MALE,4100.0
219,Chinstrap,Dream,18.7,50.2,198.0,FEMALE,3775.0

# Grouping Data

We can use specific methods to return useful information about our dataset or a particular series. For example, the <b>median()</b> method returns the median of each column. However, this only works if the values are numerical, so we have to specify valid columns in the method to avoid a type error.

In [62]:
df.median

<bound method DataFrame.median of     species     island  culmen_depth_mm  culmen_length_mm  flipper_length_mm  \
0    Adelie  Torgersen             18.7              39.1              181.0
1    Adelie  Torgersen             17.4              39.5              186.0
2    Adelie  Torgersen             18.0              40.3              195.0
3    Adelie  Torgersen              NaN               NaN                NaN
4    Adelie  Torgersen             19.3              36.7              193.0
..      ...        ...              ...               ...                ...
339  Gentoo     Biscoe              NaN               NaN                NaN
340  Gentoo     Biscoe             14.3              46.8              215.0
341  Gentoo     Biscoe             15.7              50.4              222.0
342  Gentoo     Biscoe             14.8              45.2              212.0
343  Gentoo     Biscoe             16.1              49.9              213.0

        sex  body_mass_g
0      MALE       3750.0
1    FEMALE       3800.0
2    FEMALE       3250.0
3       NaN          NaN
4    FEMALE       3450.0
..      ...          ...
339     NaN          NaN
340  FEMALE       4850.0
341    MALE       5750.0
342  FEMALE       5200.0
343    MALE       5400.0

[344 rows x 7 columns]>

In [64]:
df['body_mass_g'].median()

np.float64(4050.0)

In [65]:
df[['body_mass_g', 'culmen_depth_mm']].median()

body_mass_g        4050.0
culmen_depth_mm      17.3
dtype: float64

The <b>describe()</b> method outputs multiple statistics about each column. 
Note: The percentages are percentile values.

In [66]:
df.describe()

       culmen_depth_mm  culmen_length_mm  flipper_length_mm  body_mass_g
count       342.000000        342.000000         342.000000   342.000000
mean         17.151170         43.921930         200.915205  4201.754386
std           1.974793          5.459584          14.061714   801.954536
min          13.100000         32.100000         172.000000  2700.000000
25%          15.600000         39.225000         190.000000  3550.000000
50%          17.300000         44.450000         197.000000  4050.000000
75%          18.700000         48.500000         213.000000  4750.000000
max          21.500000         59.600000         231.000000  6300.000000

The <b>value_counts()</b> method returns a series that contains the values and the number of occurrences of that value.

In [67]:
df['body_mass_g'].value_counts()

body_mass_g
3800.0    12
3700.0    11
3900.0    10
3950.0    10
3550.0     9
          ..
4475.0     1
3975.0     1
3575.0     1
3850.0     1
5750.0     1
Name: count, Length: 94, dtype: int64

<b>value_counts(normalize=True)</b> returns the percentage of how often a value occurs.

The <b>groupby()</b> method is used to generate a new dataframe based on specific criteria. It involves splitting an object, applying a function, and obtaining the results.

In [68]:
sex_M = df.groupby(['sex'])

In [69]:
type(sex_M)

pandas.core.groupby.generic.DataFrameGroupBy

In [70]:
sex_M.get_group('MALE')

/var/folders/wb/_b22zyw974s0hkz5r73lw6ph0000gn/T/ipykernel_38527/2917788816.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sex_M.get_group('MALE')

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Adelie,Torgersen,18.7,39.1,181.0,MALE,3750.0
5,Adelie,Torgersen,20.6,39.3,190.0,MALE,3650.0
7,Adelie,Torgersen,19.6,39.2,195.0,MALE,4675.0
13,Adelie,Torgersen,21.2,38.6,191.0,MALE,3800.0
14,Adelie,Torgersen,21.1,34.6,198.0,MALE,4400.0
...,...,...,...,...,...,...,...
333,Gentoo,Biscoe,16.3,51.5,230.0,MALE,5500.0
335,Gentoo,Biscoe,16.0,55.1,230.0,MALE,5850.0
337,Gentoo,Biscoe,16.2,48.8,222.0,MALE,6000.0
341,Gentoo,Biscoe,15.7,50.4,222.0,MALE,5750.0
343,Gentoo,Biscoe,16.1,49.9,213.0,MALE,5400.0

In [72]:
sex_M.get_group('FEMALE')

/var/folders/wb/_b22zyw974s0hkz5r73lw6ph0000gn/T/ipykernel_38527/3428651839.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sex_M.get_group('FEMALE')

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
1,Adelie,Torgersen,17.4,39.5,186.0,FEMALE,3800.0
2,Adelie,Torgersen,18.0,40.3,195.0,FEMALE,3250.0
4,Adelie,Torgersen,19.3,36.7,193.0,FEMALE,3450.0
6,Adelie,Torgersen,17.8,38.9,181.0,FEMALE,3625.0
12,Adelie,Torgersen,17.6,41.1,182.0,FEMALE,3200.0
...,...,...,...,...,...,...,...
332,Gentoo,Biscoe,15.2,43.5,213.0,FEMALE,4650.0
334,Gentoo,Biscoe,14.1,46.2,217.0,FEMALE,4375.0
338,Gentoo,Biscoe,13.7,47.2,214.0,FEMALE,4925.0
340,Gentoo,Biscoe,14.3,46.8,215.0,FEMALE,4850.0
342,Gentoo,Biscoe,14.8,45.2,212.0,FEMALE,5200.0

So, using the <b>get_group()</b> method we are able to obtain a dataframe that only contains the male penguins.

We can also use the <b>apply()</b> method to input a specific function to each row or column.

In [71]:
sex_M['body_mass_g'].apply(lambda x: (x.sum()))

sex
.           4875.0
FEMALE    637275.0
MALE      763675.0
Name: body_mass_g, dtype: float64

The lambda function is a built-in Python function that allows one to write a loop in a single line.

We can also combine more than one series in pandas using the <b>concat()</b> method.<br>
It is how we implement it: <b>pd.concat([list of series you want to combine], axis='columns or rows', sort=False]</b>.

# Cleaning Data

We can remove rows with missing values using the <b>dropna()</b> method. The default parameters working in the background are <b>dropna(axis='index', how='any')</b>. We can set the axis to either 'index' (drop the row) or 'columns' (drop the column). The 'any' parameter says that 'any' row or column with a missing value gets dropped. We can change this to 'all,' meaning we only remove a missing value if the entire row or column is filled with missing values.

In [73]:
df

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Adelie,Torgersen,18.7,39.1,181.0,MALE,3750.0
1,Adelie,Torgersen,17.4,39.5,186.0,FEMALE,3800.0
2,Adelie,Torgersen,18.0,40.3,195.0,FEMALE,3250.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,19.3,36.7,193.0,FEMALE,3450.0
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,14.3,46.8,215.0,FEMALE,4850.0
341,Gentoo,Biscoe,15.7,50.4,222.0,MALE,5750.0
342,Gentoo,Biscoe,14.8,45.2,212.0,FEMALE,5200.0
343,Gentoo,Biscoe,16.1,49.9,213.0,MALE,5400.0

In [74]:
df.dropna(axis='index', how='any')

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Adelie,Torgersen,18.7,39.1,181.0,MALE,3750.0
1,Adelie,Torgersen,17.4,39.5,186.0,FEMALE,3800.0
2,Adelie,Torgersen,18.0,40.3,195.0,FEMALE,3250.0
4,Adelie,Torgersen,19.3,36.7,193.0,FEMALE,3450.0
5,Adelie,Torgersen,20.6,39.3,190.0,MALE,3650.0
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,13.7,47.2,214.0,FEMALE,4925.0
340,Gentoo,Biscoe,14.3,46.8,215.0,FEMALE,4850.0
341,Gentoo,Biscoe,15.7,50.4,222.0,MALE,5750.0
342,Gentoo,Biscoe,14.8,45.2,212.0,FEMALE,5200.0
343,Gentoo,Biscoe,16.1,49.9,213.0,MALE,5400.0

In [75]:
df.dropna(axis = 'index', how = 'all')

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Adelie,Torgersen,18.7,39.1,181.0,MALE,3750.0
1,Adelie,Torgersen,17.4,39.5,186.0,FEMALE,3800.0
2,Adelie,Torgersen,18.0,40.3,195.0,FEMALE,3250.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,19.3,36.7,193.0,FEMALE,3450.0
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,14.3,46.8,215.0,FEMALE,4850.0
341,Gentoo,Biscoe,15.7,50.4,222.0,MALE,5750.0
342,Gentoo,Biscoe,14.8,45.2,212.0,FEMALE,5200.0
343,Gentoo,Biscoe,16.1,49.9,213.0,MALE,5400.0

In [77]:
df.dropna(axis = 'columns', how = 'any')

    species     island
0    Adelie  Torgersen
1    Adelie  Torgersen
2    Adelie  Torgersen
3    Adelie  Torgersen
4    Adelie  Torgersen
..      ...        ...
339  Gentoo     Biscoe
340  Gentoo     Biscoe
341  Gentoo     Biscoe
342  Gentoo     Biscoe
343  Gentoo     Biscoe

[344 rows x 2 columns]

In [76]:
df.dropna(axis = 'columns', how = 'all')

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Adelie,Torgersen,18.7,39.1,181.0,MALE,3750.0
1,Adelie,Torgersen,17.4,39.5,186.0,FEMALE,3800.0
2,Adelie,Torgersen,18.0,40.3,195.0,FEMALE,3250.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,19.3,36.7,193.0,FEMALE,3450.0
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,14.3,46.8,215.0,FEMALE,4850.0
341,Gentoo,Biscoe,15.7,50.4,222.0,MALE,5750.0
342,Gentoo,Biscoe,14.8,45.2,212.0,FEMALE,5200.0
343,Gentoo,Biscoe,16.1,49.9,213.0,MALE,5400.0

You can also pass a subset into the <b>dropna()</b> method. Then only this subset is checked for missing values to drop across a specific column: <b>dropna(axis='index', subset =['sex'])</b>. Note that the square brackets imply a list of specified columns. Also, the 'how' parameter is not needed here because we are only dropping rows that are missing the values in the 'sex' column, which makes the' how' parameter redundant.

In [78]:
df.dropna(axis = 'index', subset = ['sex'])

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Adelie,Torgersen,18.7,39.1,181.0,MALE,3750.0
1,Adelie,Torgersen,17.4,39.5,186.0,FEMALE,3800.0
2,Adelie,Torgersen,18.0,40.3,195.0,FEMALE,3250.0
4,Adelie,Torgersen,19.3,36.7,193.0,FEMALE,3450.0
5,Adelie,Torgersen,20.6,39.3,190.0,MALE,3650.0
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,13.7,47.2,214.0,FEMALE,4925.0
340,Gentoo,Biscoe,14.3,46.8,215.0,FEMALE,4850.0
341,Gentoo,Biscoe,15.7,50.4,222.0,MALE,5750.0
342,Gentoo,Biscoe,14.8,45.2,212.0,FEMALE,5200.0
343,Gentoo,Biscoe,16.1,49.9,213.0,MALE,5400.0

The library <b>numpy</b> is helpful here. This library provides tools to directly refer to the missing 'NaN' values.

In [79]:
import numpy as np

Now, we can have missing values written differently due to different software - instead of 'NaN,' it can be written as 'missing' or 'not available.'

It can be fixed using the replace method, for example, <b>df.replace('name-of-the-missing-variable', np.NaN, inplace=True)</b>.

It replaces the missing variable names with 'NaN,' which can then be removed using the <b>dropna()</b> method.

The reverse of this operation is the <b>fillna()</b> method.
We insert, as an argument, a string or integer, which we would like to replace the NaN value with - <b>fillna("NOT PRESENT")</b>.

Another convenient method is the <b>isna()</b>. It returns a dataframe where the values are replaced with true or false values, with true being a NaN value.

Note that the missing value NaN is a float. If we need to perform numerical operations with some data that have missing values, we need to convert them to a float to account for the NaN values. We  convert types by using type casting: <b>df['column-name'] = df['column-name'].astype(float)</b>.

We can also quickly identify the strings within a column using the <b>unique()</b> method for a series. It lets us identify certain strings that cannot be turned into a 'float' - we can replace them with the <b>replace()</b> method.

In [80]:
df

,species,island,culmen_depth_mm,culmen_length_mm,flipper_length_mm,sex,body_mass_g
0,Adelie,Torgersen,18.7,39.1,181.0,MALE,3750.0
1,Adelie,Torgersen,17.4,39.5,186.0,FEMALE,3800.0
2,Adelie,Torgersen,18.0,40.3,195.0,FEMALE,3250.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,19.3,36.7,193.0,FEMALE,3450.0
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,14.3,46.8,215.0,FEMALE,4850.0
341,Gentoo,Biscoe,15.7,50.4,222.0,MALE,5750.0
342,Gentoo,Biscoe,14.8,45.2,212.0,FEMALE,5200.0
343,Gentoo,Biscoe,16.1,49.9,213.0,MALE,5400.0

In [81]:
df['island'].unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [ ]:
# Some cells might have empty values, where there is no value indicated, we can set a 0 there or fill in a value ourselves
# We have some functions to do that particular action (as described above)