# Plotly Tutorial

Plotly is an interactive open source data visualiztion library in Pyhon, it supports over 40 unique chrt types that cover a wide range of statistical, financial, geographic, scientific and 3-dimensional use cases.

To get more information on Plotly here isa link to their official website : https://plotly.com/python/

To get started with plotly run the following command in your jupter notebook : !pip install plotly

In [11]:
# pip install plotly

In [12]:
# pip install jupyter

Defaulting to user installation because normal site-packages is not writeable
Collecting jupyter
  Downloading jupyter-1.1.1-py2.py3-none-any.whl (2.7 kB)
Requirement already satisfied: ipykernel in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jupyter) (6.31.0)
Collecting notebook
  Downloading notebook-7.5.2-py3-none-any.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 23.4 MB/s eta 0:00:01   |▎                               | 133 kB 1.0 MB/s eta 0:00:14     |███████████████████             | 8.6 MB 23.4 MB/s eta 0:00:01     |█████████████████████████▋      | 11.6 MB 23.4 MB/s eta 0:00:01     |██████████████████████████▉     | 12.1 MB 23.4 MB/s eta 0:00:01     |███████████████████████████████ | 14.0 MB 23.4 MB/s eta 0:00:01
Collecting nbconvert
  Downloading nbconvert-7.16.6-py3-none-any.whl (258 kB)
     |████████████████████████████████| 258 kB 18.8 MB/s eta 0:00:01
Collecting jupyter-console
  Downloading jupyter_console-6.6.3-py3-none-any.whl (24 kB)
Collecting ipywidgets
  Downloading ipywidgets-8.1.8-py3-none-any.whl (139 kB)
     |████████████████████████████████| 139 kB 10.0 MB/s eta 0:00:01
Collecting jupyterlab
  Downloading jupyterlab-4.5.2-py3-none-any.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 19.1 MB/s eta 0:00:01
Requirement already satisfied: nest-asyncio>=1.4 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: appnope>=0.1.2 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel->jupyter) (0.1.4)
Requirement already satisfied: traitlets>=5.4.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel->jupyter) (5.14.3)
Requirement already satisfied: tornado>=6.2 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel->jupyter) (6.5.4)
Requirement already satisfied: ipython>=7.23.1 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel->jupyter) (8.18.1)
Requirement already satisfied: jupyter-client>=8.0.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel->jupyter) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel->jupyter) (5.8.1)
Requirement already satisfied: matplotlib-inline>=0.1 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel->jupyter) (0.2.1)
Requirement already satisfied: psutil>=5.7 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel->jupyter) (7.2.1)
Requirement already satisfied: packaging>=22 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel->jupyter) (25.0)
Requirement already satisfied: pyzmq>=25 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: comm>=0.1.1 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel->jupyter) (1.8.19)
Requirement already satisfied: exceptiongroup in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.3.1)
Requirement already satisfied: jedi>=0.16 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.19.2)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.52)
Requirement already satisfied: stack-data in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: typing-extensions in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (4.15.0)
Requirement already satisfied: pexpect>4.3 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (4.9.0)
Requirement already satisfied: pygments>=2.4.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.19.2)
Requirement already satisfied: decorator in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.2.1)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter) (0.8.5)
Requirement already satisfied: importlib-metadata>=4.8.3 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jupyter-client>=8.0.0->ipykernel->jupyter) (8.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jupyter-client>=8.0.0->ipykernel->jupyter) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from importlib-metadata>=4.8.3->jupyter-client>=8.0.0->ipykernel->jupyter) (3.23.0)
Requirement already satisfied: platformdirs>=2.5 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (4.4.0)
Requirement already satisfied: ptyprocess>=0.5 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel->jupyter) (0.7.0)
Requirement already satisfied: wcwidth in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.2.14)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.0.0->ipykernel->jupyter) (1.15.0)
Collecting widgetsnbextension~=4.0.14
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 9.6 MB/s eta 0:00:01
Collecting jupyterlab_widgets~=3.0.15
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
     |████████████████████████████████| 914 kB 11.6 MB/s eta 0:00:01
Collecting jinja2>=3.0.3
  Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
     |████████████████████████████████| 134 kB 12.9 MB/s eta 0:00:01
Collecting jupyterlab-server<3,>=2.28.0
  Downloading jupyterlab_server-2.28.0-py3-none-any.whl (59 kB)
     |████████████████████████████████| 59 kB 15.1 MB/s eta 0:00:01
Collecting httpx<1,>=0.25.0
  Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
     |████████████████████████████████| 73 kB 2.3 MB/s eta 0:00:011
Collecting jupyter-server<3,>=2.4.0
  Downloading jupyter_server-2.17.0-py3-none-any.whl (388 kB)
     |████████████████████████████████| 388 kB 8.6 MB/s eta 0:00:01
Collecting async-lru>=1.0.0
  Downloading async_lru-2.0.5-py3-none-any.whl (6.1 kB)
Collecting tomli>=1.2.2
  Downloading tomli-2.4.0-py3-none-any.whl (14 kB)
Collecting jupyter-lsp>=2.0.0
  Downloading jupyter_lsp-2.3.0-py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 8.3 MB/s  eta 0:00:01
Collecting notebook-shim>=0.2
  Downloading notebook_shim-0.2.4-py3-none-any.whl (13 kB)
Requirement already satisfied: setuptools>=41.1.0 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from jupyterlab->jupyter) (58.0.4)
Collecting certifi
  Downloading certifi-2026.1.4-py3-none-any.whl (152 kB)
     |████████████████████████████████| 152 kB 7.3 MB/s eta 0:00:01
Collecting anyio
  Downloading anyio-4.12.1-py3-none-any.whl (113 kB)
     |████████████████████████████████| 113 kB 8.6 MB/s eta 0:00:01
Collecting httpcore==1.*
  Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 8.1 MB/s eta 0:00:01
Collecting idna
  Downloading idna-3.11-py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 9.6 MB/s  eta 0:00:01
Collecting h11>=0.16
  Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Collecting MarkupSafe>=2.0
  Downloading markupsafe-3.0.3-cp39-cp39-macosx_11_0_arm64.whl (12 kB)
Collecting send2trash>=1.8.2
  Downloading send2trash-2.1.0-py3-none-any.whl (17 kB)
Collecting nbformat>=5.3.0
  Using cached nbformat-5.10.4-py3-none-any.whl (78 kB)
Collecting prometheus-client>=0.9
  Downloading prometheus_client-0.24.1-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 3.8 MB/s eta 0:00:011
Collecting jupyter-server-terminals>=0.4.4
  Downloading jupyter_server_terminals-0.5.4-py3-none-any.whl (13 kB)
Collecting overrides>=5.0
  Downloading overrides-7.7.0-py3-none-any.whl (17 kB)
Collecting terminado>=0.8.3
  Downloading terminado-0.18.1-py3-none-any.whl (14 kB)
Collecting argon2-cffi>=21.1
  Downloading argon2_cffi-25.1.0-py3-none-any.whl (14 kB)
Collecting websocket-client>=1.7
  Downloading websocket_client-1.9.0-py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 1.8 MB/s eta 0:00:01
Collecting jupyter-events>=0.11.0
  Downloading jupyter_events-0.12.0-py3-none-any.whl (19 kB)
Collecting argon2-cffi-bindings
  Downloading argon2_cffi_bindings-25.1.0-cp39-abi3-macosx_11_0_arm64.whl (31 kB)
Collecting rfc3339-validator
  Downloading rfc3339_validator-0.1.4-py2.py3-none-any.whl (3.5 kB)
Collecting pyyaml>=5.3
  Downloading pyyaml-6.0.3-cp39-cp39-macosx_11_0_arm64.whl (174 kB)
     |████████████████████████████████| 174 kB 4.5 MB/s eta 0:00:01     |██████████████████▉             | 102 kB 4.5 MB/s eta 0:00:01
Requirement already satisfied: referencing in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.36.2)
Collecting rfc3986-validator>=0.1.1
  Downloading rfc3986_validator-0.1.1-py2.py3-none-any.whl (4.2 kB)
Requirement already satisfied: jsonschema[format-nongpl]>=4.18.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (4.25.1)
Collecting python-json-logger>=2.0.4
  Downloading python_json_logger-4.0.0-py3-none-any.whl (15 kB)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.27.1)
Requirement already satisfied: attrs>=22.2.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2025.9.1)
Collecting isoduration
  Downloading isoduration-20.11.0-py3-none-any.whl (11 kB)
Collecting jsonpointer>1.13
  Downloading jsonpointer-3.0.0-py2.py3-none-any.whl (7.6 kB)
Collecting uri-template
  Downloading uri_template-1.3.0-py3-none-any.whl (11 kB)
Collecting rfc3987-syntax>=1.1.0
  Downloading rfc3987_syntax-1.1.0-py3-none-any.whl (8.0 kB)
Collecting fqdn
  Downloading fqdn-1.5.1-py3-none-any.whl (9.1 kB)
Collecting webcolors>=24.6.0
  Downloading webcolors-24.11.1-py3-none-any.whl (14 kB)
Collecting babel>=2.10
  Downloading babel-2.17.0-py3-none-any.whl (10.2 MB)
     |████████████████████████████████| 10.2 MB 5.9 MB/s eta 0:00:01    |▎                               | 81 kB 5.8 MB/s eta 0:00:02     |███                             | 952 kB 5.9 MB/s eta 0:00:02     |████▍                           | 1.4 MB 5.9 MB/s eta 0:00:02
Collecting requests>=2.31
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 7.7 MB/s  eta 0:00:01
Collecting json5>=0.9.0
  Downloading json5-0.13.0-py3-none-any.whl (36 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
     |████████████████████████████████| 107 kB 25.2 MB/s eta 0:00:01
Collecting pandocfilters>=1.4.1
  Downloading pandocfilters-1.5.1-py2.py3-none-any.whl (8.7 kB)
Collecting nbclient>=0.5.0
  Downloading nbclient-0.10.2-py3-none-any.whl (25 kB)
Collecting jupyterlab-pygments
  Downloading jupyterlab_pygments-0.3.0-py3-none-any.whl (15 kB)
Collecting mistune<4,>=2.0.3
  Downloading mistune-3.2.0-py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 2.3 MB/s eta 0:00:01
Collecting defusedxml
  Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting bleach[css]!=5.0.0
  Downloading bleach-6.2.0-py3-none-any.whl (163 kB)
     |████████████████████████████████| 163 kB 17.3 MB/s eta 0:00:01
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting tinycss2<1.5,>=1.1.0
  Downloading tinycss2-1.4.0-py3-none-any.whl (26 kB)
Requirement already satisfied: fastjsonschema>=2.15 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.21.2)
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.4-cp39-cp39-macosx_10_9_universal2.whl (209 kB)
     |████████████████████████████████| 209 kB 12.4 MB/s eta 0:00:01
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 39.4 MB/s eta 0:00:01
Collecting lark>=1.2.2
  Downloading lark-1.3.1-py3-none-any.whl (113 kB)
     |████████████████████████████████| 113 kB 6.7 MB/s eta 0:00:01
Collecting cffi>=1.0.1
  Downloading cffi-2.0.0-cp39-cp39-macosx_11_0_arm64.whl (180 kB)
     |████████████████████████████████| 180 kB 5.3 MB/s eta 0:00:01
Collecting pycparser
  Downloading pycparser-2.23-py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB 13.9 MB/s eta 0:00:01
Collecting soupsieve>=1.6.1
  Downloading soupsieve-2.8.1-py3-none-any.whl (36 kB)
Collecting arrow>=0.15.0
  Downloading arrow-1.4.0-py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 13.2 MB/s eta 0:00:01
Requirement already satisfied: tzdata in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2025.3)
Requirement already satisfied: pure-eval in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Requirement already satisfied: executing>=1.2.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (3.0.1)
Installing collected packages: webencodings, pycparser, lark, arrow, webcolors, uri-template, tinycss2, soupsieve, rfc3987-syntax, rfc3986-validator, rfc3339-validator, nbformat, MarkupSafe, jsonpointer, isoduration, idna, fqdn, cffi, bleach, terminado, pyyaml, python-json-logger, pandocfilters, nbclient, mistune, jupyterlab-pygments, jinja2, defusedxml, beautifulsoup4, argon2-cffi-bindings, websocket-client, urllib3, send2trash, prometheus-client, overrides, nbconvert, jupyter-server-terminals, jupyter-events, h11, charset-normalizer, certifi, argon2-cffi, anyio, requests, jupyter-server, json5, httpcore, babel, tomli, notebook-shim, jupyterlab-server, jupyter-lsp, httpx, async-lru, widgetsnbextension, jupyterlab-widgets, jupyterlab, notebook, jupyter-console, ipywidgets, jupyter
  Attempting uninstall: nbformat
    Found existing installation: nbformat 4.2.0
    Uninstalling nbformat-4.2.0:
      Successfully uninstalled nbformat-4.2.0
Successfully installed MarkupSafe-3.0.3 anyio-4.12.1 argon2-cffi-25.1.0 argon2-cffi-bindings-25.1.0 arrow-1.4.0 async-lru-2.0.5 babel-2.17.0 beautifulsoup4-4.14.3 bleach-6.2.0 certifi-2026.1.4 cffi-2.0.0 charset-normalizer-3.4.4 defusedxml-0.7.1 fqdn-1.5.1 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 idna-3.11 ipywidgets-8.1.8 isoduration-20.11.0 jinja2-3.1.6 json5-0.13.0 jsonpointer-3.0.0 jupyter-1.1.1 jupyter-console-6.6.3 jupyter-events-0.12.0 jupyter-lsp-2.3.0 jupyter-server-2.17.0 jupyter-server-terminals-0.5.4 jupyterlab-4.5.2 jupyterlab-pygments-0.3.0 jupyterlab-server-2.28.0 jupyterlab-widgets-3.0.16 lark-1.3.1 mistune-3.2.0 nbclient-0.10.2 nbconvert-7.16.6 nbformat-5.10.4 notebook-7.5.2 notebook-shim-0.2.4 overrides-7.7.0 pandocfilters-1.5.1 prometheus-client-0.24.1 pycparser-2.23 python-json-logger-4.0.0 pyyaml-6.0.3 requests-2.32.5 rfc3339-validator-0.1.4 rfc3986-validator-0.1.1 rfc3987-syntax-1.1.0 send2trash-2.1.0 soupsieve-2.8.1 terminado-0.18.1 tinycss2-1.4.0 tomli-2.4.0 uri-template-1.3.0 urllib3-2.6.3 webcolors-24.11.1 webencodings-0.5.1 websocket-client-1.9.0 widgetsnbextension-4.0.15
WARNING: You are using pip version 21.2.4; however, version 25.3 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [13]:
# !pip install plotly
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects  as go
from plotly.subplots import make_subplots

In [14]:
print(pd.__version__)

2.3.3

In [15]:
df = pd.read_csv('data/penguins_size.csv')

In [16]:
df = df.drop(axis = 0, index = 336)
df_clean = df.dropna(axis = 'index', how = 'any')
df_clean.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE

When working with plotly you have to make sure your data set is clean and you do not have any 'NaN' values. Using the Pandas dropna method we can clean our data set.

# Interactive Scatter Plot

Plotly is an interactive data visualization library. We will illustrate this with a multitude of plots starting off with a basic scatter plot

Hovering over each data point on the plot will reveal data about the penguin's body mass and culmen length which correspond to the x and y axis. Similar to Seaborn we can color each parameter to encode categorical data.

In [17]:
pip install ipykernel

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ipykernel in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (6.31.0)
Requirement already satisfied: pyzmq>=25 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: appnope>=0.1.2 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (0.1.4)
Requirement already satisfied: matplotlib-inline>=0.1 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: ipython>=7.23.1 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (8.18.1)
Requirement already satisfied: traitlets>=5.4.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: tornado>=6.2 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (6.5.4)
Requirement already satisfied: comm>=0.1.1 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: psutil>=5.7 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (7.2.1)
Requirement already satisfied: packaging>=22 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (25.0)
Requirement already satisfied: nest-asyncio>=1.4 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (5.8.1)
Requirement already satisfied: debugpy>=1.6.5 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (1.8.19)
Requirement already satisfied: jupyter-client>=8.0.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (8.6.3)
Requirement already satisfied: pexpect>4.3 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel) (4.9.0)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel) (2.19.2)
Requirement already satisfied: jedi>=0.16 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: exceptiongroup in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel) (1.3.1)
Requirement already satisfied: decorator in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: stack-data in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: typing-extensions in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython>=7.23.1->ipykernel) (4.15.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel) (0.8.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jupyter-client>=8.0.0->ipykernel) (2.9.0.post0)
Requirement already satisfied: importlib-metadata>=4.8.3 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jupyter-client>=8.0.0->ipykernel) (8.7.1)
Requirement already satisfied: zipp>=3.20 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from importlib-metadata>=4.8.3->jupyter-client>=8.0.0->ipykernel) (3.23.0)
Requirement already satisfied: platformdirs>=2.5 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (4.4.0)
Requirement already satisfied: ptyprocess>=0.5 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel) (0.7.0)
Requirement already satisfied: wcwidth in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.2.14)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.0.0->ipykernel) (1.15.0)
Requirement already satisfied: asttokens>=2.1.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython>=7.23.1->ipykernel) (3.0.1)
Requirement already satisfied: executing>=1.2.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: pure-eval in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython>=7.23.1->ipykernel) (0.2.3)
WARNING: You are using pip version 21.2.4; however, version 25.3 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [21]:
pip install --upgrade nbformat

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nbformat in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (4.2.0)
Collecting nbformat
  Using cached nbformat-5.10.4-py3-none-any.whl (78 kB)
Requirement already satisfied: traitlets>=5.1 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from nbformat) (5.14.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from nbformat) (5.8.1)
Requirement already satisfied: fastjsonschema>=2.15 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from nbformat) (4.25.1)
Requirement already satisfied: attrs>=22.2.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat) (0.27.1)
Requirement already satisfied: platformdirs>=2.5 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.4.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)
Installing collected packages: nbformat
  Attempting uninstall: nbformat
    Found existing installation: nbformat 4.2.0
    Uninstalling nbformat-4.2.0:
      Successfully uninstalled nbformat-4.2.0
Successfully installed nbformat-5.10.4
WARNING: You are using pip version 21.2.4; however, version 25.3 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [26]:
import plotly.io as pio

pio.renderers.default = "vscode"
pio.renderers.default = "notebook"

In [29]:
import nbformat, IPython
print(nbformat.__version__)
print(IPython.__version__)

import sys
!{sys.executable} -m pip install -U plotly nbformat ipython ipykernel

4.2.0
8.18.1
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (6.5.2)
Requirement already satisfied: nbformat in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (5.10.4)
Requirement already satisfied: ipython in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (8.18.1)
Requirement already satisfied: ipykernel in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (6.31.0)
Requirement already satisfied: packaging in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from plotly) (25.0)
Requirement already satisfied: narwhals>=1.15.1 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from plotly) (2.15.0)
Requirement already satisfied: fastjsonschema>=2.15 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from nbformat) (2.21.2)
Requirement already satisfied: traitlets>=5.1 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from nbformat) (5.14.3)
Requirement already satisfied: jsonschema>=2.6 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from nbformat) (4.25.1)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from nbformat) (5.8.1)
Requirement already satisfied: exceptiongroup in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython) (1.3.1)
Requirement already satisfied: pexpect>4.3 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython) (4.9.0)
Requirement already satisfied: matplotlib-inline in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython) (0.2.1)
Requirement already satisfied: decorator in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython) (5.2.1)
Requirement already satisfied: jedi>=0.16 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython) (0.19.2)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython) (3.0.52)
Requirement already satisfied: stack-data in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython) (0.6.3)
Requirement already satisfied: pygments>=2.4.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython) (2.19.2)
Requirement already satisfied: typing-extensions in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipython) (4.15.0)
Requirement already satisfied: jupyter-client>=8.0.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (8.6.3)
Requirement already satisfied: comm>=0.1.1 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (1.8.19)
Requirement already satisfied: nest-asyncio>=1.4 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: tornado>=6.2 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (6.5.4)
Requirement already satisfied: psutil>=5.7 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (7.2.1)
Requirement already satisfied: appnope>=0.1.2 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (0.1.4)
Requirement already satisfied: pyzmq>=25 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jedi>=0.16->ipython) (0.8.5)
Requirement already satisfied: referencing>=0.28.4 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat) (0.27.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: attrs>=22.2.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: importlib-metadata>=4.8.3 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jupyter-client>=8.0.0->ipykernel) (8.7.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jupyter-client>=8.0.0->ipykernel) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from importlib-metadata>=4.8.3->jupyter-client>=8.0.0->ipykernel) (3.23.0)
Requirement already satisfied: platformdirs>=2.5 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.4.0)
Requirement already satisfied: ptyprocess>=0.5 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from pexpect>4.3->ipython) (0.7.0)
Requirement already satisfied: wcwidth in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython) (0.2.14)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.0.0->ipykernel) (1.15.0)
Requirement already satisfied: pure-eval in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython) (0.2.3)
Requirement already satisfied: asttokens>=2.1.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython) (3.0.1)
Requirement already satisfied: executing>=1.2.0 in /Users/toloosha/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython) (2.2.1)
WARNING: You are using pip version 21.2.4; however, version 25.3 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [47]:
import plotly.io as pio
pio.renderers.default = "browser"   # or "vscode"


import plotly.io as pio
pio.renderers

Renderers configuration
-----------------------
    Default renderer: 'browser'
    Available renderers:
        ['plotly_mimetype', 'jupyterlab', 'nteract', 'vscode',
         'notebook', 'notebook_connected', 'kaggle', 'azure', 'colab',
         'cocalc', 'databricks', 'json', 'png', 'jpeg', 'jpg', 'svg',
         'pdf', 'browser', 'firefox', 'chrome', 'chromium', 'iframe',
         'iframe_connected', 'sphinx_gallery', 'sphinx_gallery_png']

In [49]:
figure = px.scatter(df_clean, x = 'body_mass_g', y = 'culmen_length_mm', color = 'sex')
figure.show()

Here we have modified the plot to express more things, by setting the 'size' parameter equal to 'flipper_length_mm' the size of each point now scales with flipper length. There is also the 'hover_data' parameter which is used to show extra data about each point, and finally the hover_name parameter is used to emphasize certain data about each point.

In [51]:
figure = px.scatter(df_clean, x = 'body_mass_g', y = 'culmen_depth_mm', color = 'island',
                    size = 'flipper_length_mm', hover_data = ['culmen_depth_mm','sex'],hover_name = 'species')
figure.show()

The color parameter may also be used for continuous data rather than just categorical data.

In [52]:
figure = px.scatter(df_clean, x = "body_mass_g", y = "culmen_length_mm", color = 'flipper_length_mm', hover_data=['sex'] )
figure.show()

Similar to Seaborn's pairplot function plotly's scatter_matrix() function can be used to plot all the numerical data against each other, however, you can specify which columns to apply using the dimension parameter.

In [54]:
# if pandas >= 2.0
pd.DataFrame.iteritems = pd.DataFrame.items

In [55]:
figure = px.scatter_matrix(df_clean, dimensions = ['culmen_length_mm', 'culmen_depth_mm', 'flipper_length_mm', 'body_mass_g'], color = 'species')
figure.update_layout(width = 800, height = 1000)
figure.show()

Additionally you can remove plots that plot columns against itself using the 'figure.update_traces(diagonal_visible = False)' function.

In [53]:
figure = px.scatter_matrix(df_clean, dimensions = ['culmen_length_mm', 'culmen_depth_mm', 'flipper_length_mm', 'body_mass_g'], color = 'species')
figure.update_traces(diagonal_visible = False)
figure.update_layout(width = 800, height = 1000)
figure.show()

You can generate a three-dimensional scatter plot. This is similar to the two-dimensional version as they have similar parameters except for the extra z parameter.

In [56]:
figure = px.scatter_3d(df_clean, x = 'body_mass_g', y = 'sex', z = 'culmen_length_mm', 
                       color = 'species', size = 'flipper_length_mm',
                       hover_data = ['culmen_depth_mm','sex'],hover_name = 'island')
figure.show()

# Histogram / Bar Graph

Using the px function and the bar method we can create a bar graph and specify the axis with 'x' and 'y' parameters.

In [57]:
figure = px.bar(df_clean, x = 'body_mass_g', y = 'flipper_length_mm')
figure.show()

We can graph multiple bar graphs by inserting a list of series into the y parameter

In [58]:
figure = px.bar(df_clean, x = 'body_mass_g', y = ['culmen_length_mm', 'culmen_depth_mm', 'flipper_length_mm'], title = 'Wide Example')
figure.show()

Here we change the graph by using colours to separate the different islands.

In [59]:
figure = px.bar(df_clean, x='sex', y = 'body_mass_g', color = 'island')
figure.show()

Histograms are very similar to bar graphs. For the most part you can swap between them by simply switching the bar method for the histogram method.

In [60]:
figure = px.histogram(df_clean, x = 'island', y = 'flipper_length_mm', color = 'sex', barmode = 'group')
figure.show()

In [61]:
figure = px.bar(df_clean, x = 'culmen_length_mm', y = 'body_mass_g', color = 'sex', barmode = 'group', 
               facet_row = 'species', facet_col = 'island')
figure.show()

# 2D Histogram

A 2D histogram which is also know as a density heatmap is the 2-D visualization of a histogram, it is useful visualizing the relationship of one attribute aginst another.

Below, there is a simple example of a 2-D Histogram. The bright spots are where there is a high count of penguins with that specific body mass and flipper length.

In [62]:
figure = px.density_heatmap(df_clean, x = 'body_mass_g', y = 'flipper_length_mm')
figure.show()

You can also plot the 2-D histogram with the respective axes distribution plots

In [63]:
figure = px.density_heatmap(df_clean, x = 'flipper_length_mm', y = 'culmen_depth_mm',
                            marginal_x = 'histogram', marginal_y = 'histogram')
figure.show()

Or you can add the count for each bin to get a better feel for the 2-D histograms distribution.

In [64]:
figure = px.density_heatmap(df_clean, x = 'culmen_depth_mm', y = 'culmen_length_mm',text_auto = True)
figure.show()

# Double Y Axis Plot

Here we will be working with two different scaled y-axis.

In [65]:
# initialize list of lists
data = [[1, 1, 60], [2, 2, 50], [3, 3, 40], [4, 4, 30], [5, 5, 20], [6, 6, 10]]
 
# Create the pandas DataFrame
df_sample = pd.DataFrame(data, columns=['x', 'y1', 'y2'])
df_sample

   x  y1  y2
0  1   1  60
1  2   2  50
2  3   3  40
3  4   4  30
4  5   5  20
5  6   6  10

In plotly you can use two differently scaled y-axis to the same x-axis by using the 'make_subplot()' function. Additionally, using the '.add_trace()' method you can assign different line plots to the different y-axis.

In [66]:
figure = make_subplots(specs = [[{'secondary_y' : True}]])

figure.add_trace(
    go.Scatter( x = df_sample['x'], y = df_sample['y1'], name = 'yaxis data 1'),
    secondary_y = False
)

figure.add_trace(
    go.Scatter( x = df_sample['x'], y = df_sample['y2'], name = 'yaxis data 2'),
    secondary_y = True
)

figure.update_layout(title_text = 'Double Y Axis Example')

figure.update_xaxes(title_text = 'x axis title')

figure.update_yaxes(title_text = 'primary y axis', secondary_y = False)
figure.update_yaxes(title_text = 'secondary y axis', secondary_y = True)

figure.show()

# Interactivity

Here we will offer some of the more interactive features plotly has to offer.

First we will demonstrate the custom button feature:

## Custom Buttons

The generation of the buttons is accomplished by setting a buttons function to plot body mass (x-axis) vs flipper length (y-axis) in a scatter plot and in a bar plot.

In [67]:
plot = go.Figure(data = [go.Scatter(x = df['body_mass_g'], y = df['flipper_length_mm'], mode ='markers')])

# Making the buttons
my_buttons = list([  
    
    dict(args =['type','scatter'] , label = 'Scatter Plot', method = 'restyle' ),
    dict(args =['type', 'bar'] , label = 'Bar Plot', method = 'restyle' )
    ])
# Your buttons are actually a list of dictionaries that describe what type of button we are dealing with.

plot.update_layout(
    updatemenus = [dict(type = 'buttons', buttons = my_buttons)]
)

plot.show()

## Sliders

Using another built-in data set that contains information about life expectancy and GDP per-capita, and using the 'animation_frame' parameter, you can create a slider that iterates through the data.

In [68]:
df_cnt = px.data.gapminder()

px.scatter(df_cnt, x="gdpPercap", y="lifeExp", animation_frame="year",
           size="pop", color="continent", hover_name="country",
           log_x=True, size_max=55, range_x=[100,100000], range_y=[25,90])

## Range Slider

In [69]:
df_stocks = px.data.stocks()
df_stocks

           date      GOOG      AAPL      AMZN        FB      NFLX      MSFT
0    2018-01-01  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
1    2018-01-08  1.018172  1.011943  1.061881  0.959968  1.053526  1.015988
2    2018-01-15  1.032008  1.019771  1.053240  0.970243  1.049860  1.020524
3    2018-01-22  1.066783  0.980057  1.140676  1.016858  1.307681  1.066561
4    2018-01-29  1.008773  0.917143  1.163374  1.018357  1.273537  1.040708
..          ...       ...       ...       ...       ...       ...       ...
100  2019-12-02  1.216280  1.546914  1.425061  1.075997  1.463641  1.720717
101  2019-12-09  1.222821  1.572286  1.432660  1.038855  1.421496  1.752239
102  2019-12-16  1.224418  1.596800  1.453455  1.104094  1.604362  1.784896
103  2019-12-23  1.226504  1.656000  1.521226  1.113728  1.567170  1.802472
104  2019-12-30  1.213014  1.678000  1.503360  1.098475  1.540883  1.788185

[105 rows x 7 columns]

In [70]:
px.line(df_stocks, x = 'date', y = 'AAPL', labels={'x':'Date', 'y':'Price'})

With a ranged slider you can select and narrow down different ranges of data.

In [71]:
x = df_stocks['date']
y = df_stocks['AAPL']

plot = go.Figure(data = [go.Scatter(x = x, y = y, mode = 'lines')])


plot.update_layout( xaxis = dict(rangeselector = dict(buttons = list([dict(count = 1, step = 'year', stepmode = 'backward')])),
                                 rangeslider = dict(visible = True)
                                )
                  )

plot.show()

By creating a data list of dictionaries we can specify a filter and plot specified values

In [72]:
import plotly.io as pio

index = df_clean.index
bodymass = df_clean['body_mass_g']

data = [dict(
  type = 'scatter',
  x = index,
  y = bodymass,
  mode = 'markers',
  transforms = [dict(
    type = 'filter',
    target = 'y',
    operation = '>', #look to see for a range
    value = 4000
  )]
)]

layout = dict(
    title = 'bodymass > 4000'
    
)

fig_dict = dict(data=data, layout=layout)


pio.show(fig_dict, validate=False)

above code borrowed from https://plotly.com/python/filter/